### ISSUE TITLE
Problem with Mozilla

### ISSUE THREAD

**Issue by ahuseyn** [JasonHeylon/react-infinite-scroll-pager#1]
Thank you for amazing solution. Currently it is the only npm module that fits my case. But when it comes to Mozilla, module behaves totally different than Chrome. It arbitrarily stops working and sometimes loading more than one page without console error. So I cannot provide any output about problem I am facing but it would be great if you check the module on Mozilla.

**Comment by JasonHeylon** [comment]
sorry for the super late response, but I just confirmed it works good with the latest Firefox now.
